version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - frontend
    networks:
      - webnet

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cocomo
      MYSQL_USER: vkharkivsk
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db/sql/initial_db.sql:/docker-entrypoint-initdb.d/initial_db.sql
      - db_data:/var/lib/mysql
    networks:
      - webnet

  app:
    build: .
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: vkharkivsk
      DB_PASSWORD: password
      DB_NAME: cocomo
    networks:
      - webnet
  
  frontend:
    build:
      context: ../cocomo-calc
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    depends_on:
      - app
    networks:
      - webnet

 
volumes:
  db_data:

networks:
  webnet: